= DocGist
Anders Nawroth

DocGist is a URL proxy tool that converts AsciiDoc documents fetched from Gists (http://gist.github.com), GitHub repositories, Dropbox folders and other sources to HTML.
The conversion to HTML is performed in the browser (client-side) using the https://github.com/asciidoctor/asciidoctor.js[Asciidoctor.js] JavaScript library

NOTE: DocGist is a hosted alternative to the Asciidoctor.js Live Preview extension for Chrome.

== Hosted Demo

See it live at http://gist.asciidoctor.org.

== Special Processing

The single addition to common AsciiDoc syntax is that links to image files will render the image and not the link, in case the link and the link text are identical.
This happens in a post-processing step after AsciiDoctor has been executed.

== History

The original idea and code for DocGist came from http://gist.neo4j.org[GraphGist].
GraphGist is an interactive documentation tool for the Neo4j database and Cypher query language.
Both tools were created by Anders Nawroth, an engineer at Neo Technology.

== Copyright and License

Copyright (C) 2013-2014 Anders Nawroth and the Asciidoctor Project.
Free use of this software is granted under the terms of the Apache License, Version 2.0.
